### PR TITLE
Fix build with tui 0.9

### LINKED ISSUE #69: Upgrade tui
We need to upgrade tui for a few features and bug fixes but there is quite a few api changes in the latest release. I've started some work on this in the upgrade-tui branch, but i've just been a little busy with some other things if anybody feels like continuing to work on it. If you make any progress feel free to open a pull request against that branch. Thanks!

### PR DESCRIPTION
**Pull request by riptl**
Minimal effort changes to make ytop build with tui-0.9.

Needs some discussion whether proposed approach of Widget ownership/borrowing is fine.

Fixes #69

### CODE REVIEW

**Comment by cjbassi** [comment]
This looks great, thanks! When you say this need some discussion, are you referring to the fact that `Widget` is implemented on references to ytop widgets? Cause that seems fine to me. Otherwise, the only other issue left is the panic that you mentioned in #69 that I need to spend more time looking at.

**Comment by riptl** [comment]
> When you say this need some discussion, are you referring to the fact that Widget is implemented on references to ytop widgets?

@cjbassi Yes, I am mainly wondering if writing implementors for references is the right approach, that's all.

```rust
impl<'a> Widget for &mut Statusbar<'a> {}
```

vs

```rust
impl<'a> Widget for Statusbar<'a> {}
```

> Cause that seems fine to me.

If you are happy with it, I am happy too though.

**Comment by cjbassi** [comment]
Yeah, I don't think the other way would work because it would consume and then drop the widget when you render it, unless you clone the widget.

**Comment by igor-raits** [comment]
@cjbassi just curious, will this make it to work with original tui (non-patched version)? I am trying to decide whether I should remove ytop from Fedora because it is not building with 0.9.x or give it a bit more time for you to port it and make it work with upstream version.

**Comment by cjbassi** [comment]
I can spend some time working on it today, there's just one bug to iron out.

**Comment by igor-raits** [comment]
@cjbassi no problem, take your time. Once you replace git repo as a dependency in a Cargo.toml, make a new release please and I'll get it updated in Fedora.

Thanks a lot!

**Comment by cjbassi** [comment]
@ignatenkobrain A new release has been published! Also thanks for packaging this in the Fedora repos.

**Comment by igor-raits** [comment]
@cjbassi amazing!

I have already submitted updates for ytop:

* [F31](https://bodhi.fedoraproject.org/updates/FEDORA-2020-b3c94ff0d5)
* [F32](https://bodhi.fedoraproject.org/updates/FEDORA-2020-4917d9c46d)

**Pull request merged**
