### PR TITLE
Fixes missing temperature on mac os

### PR DESCRIPTION
**Pull request by Zarathustra2**
Hey there,

I have fixed the missing temperature for mac os by using the same approach as used in the go version of this repo: https://github.com/cjbassi/gotop

Cheers

### CODE REVIEW

**Comment by cjbassi** [comment]
Hey, this is really great, and I would merge this, but unfortunately the C code is licensed under the GPL whereas ytop is MIT. I actually haven't been able to find any libraries that implement Mac OS temperatures to copy from, even psutil doesn't seem to have it. As a workaround for now, you could potentially use the -m flag as a way to hide the temperatures widget. Once #39 is implemented, then you can remove just the temperature widget by specifying the widget layout.

**Comment by Zarathustra2** [comment]
Ah god dam it. That is unfortunate :(

**Comment by Zarathustra2** [comment]
There is a bash command for macos:
```bash
> sudo powermetrics
```

Which runs infinitely and returns various stats including smc:
```bash
[...]
**** SMC sensors ****

CPU Thermal level: 0
GPU Thermal level: 0
IO Thermal level: 0
Fan: 1828.75 rpm
CPU die temperature: 40.31 C
GPU die temperature: 35.00 C
CPU Plimit: 0.00
GPU Plimit (Int): 0.00
Number of prochots: 0
[...]
```

Maybe a solution/workaround would be to run the command in a thread?
What do you think?

Downside: *powermetrics* must be run as sudo user... :(

**Comment by cjbassi** [comment]
That could work if ytop is run as sudo. Do you know if powermetrics is open source by the way?

**Comment by Zarathustra2** [comment]
As far as I know powermetrics is not open source, couldn't find any code. Guess under the hood it uses the same toolkit as smc.c. 

On a different note, why is ynot licensed as MIT and not GPL?
Correct me if I am wrong but the key difference between MIT and GPL is that, if anyone would use ynot in his code base he would have to make his code base open source as well. 

Since ynot is basically a stand alone program which is not meant to be included in a program why not license ynot under GPL as well?

**Comment by cjbassi** [comment]
I think the way it works is that if you copy any of the code from a GPL project into your project, the entire project has to be open sourced and GPLed, although certain parts of the codebase can be separately licensed under a different license if it is compatible with the GPL. Just because ytop is an application and not a library, doesn't mean people still can't copy code from it or create a derivative work from it. And I really don't like the gpl because it creates all of these licensing problems and imposes the gpl on people which is quite restrictive, but that's just my opinion.

**Comment by Zarathustra2** [comment]
Hey @cjbassi,

I found another library: https://github.com/GuillaumeGomez/sysinfo/ and updated my pull request!

This one is licensed under MIT and hence should not make any problems?

It looks like this:
image

It returns the temperature of the CPU, GPU and battery.

What do you think? :)

**Comment by cjbassi** [comment]
That's really nice! I must have missed that library. Thanks for figuring this out.

Can you do a couple of things and then i can merge:

1. squash the commits
2. make sysinfo a dependency only for mac. example: https://github.com/rust-psutil/rust-psutil/blob/master/Cargo.toml#L24

**Comment by Zarathustra2** [comment]
Hey,

Fixed 1) and 2) :)

**Comment by cjbassi** [comment]
Yay! Thanks a lot :) I'll make sure to get a new release out soon

**Comment by Zarathustra2** [comment]
No problem @cjbassi ! Cool program by the way, looking forward to make another PR if I can :)

BTW: I forgot to update the missing section in the readme.md. Can you do that or should I do that?

**Comment by cjbassi** [comment]
I can do that. I also need to update the change log.

**Pull request merged**
