### PR TITLE
Add Fedora installation instructions

### PR DESCRIPTION
**Pull request by tim77**

### CODE REVIEW

**Comment by cjbassi** [comment]
Thanks! Will these instructions change once https://github.com/rust-psutil/rust-psutil/issues/75 is fixed? I plan on releasing a new version soon, I'm just currently away from the computer.

**Comment by cjbassi** [comment]
Also can you explain what copr is and why that package would be more up to date? I'm not too familiar with fedora packaging...

**Comment by tim77** [comment]
> Also can you explain what copr

[Copr](https://fedoraproject.org/wiki/Category:Copr) is part of official Fedora infrastructure. Since Rust stack packaged in ugliest and awkwardest way ever in Fedora, Copr is the only sane solution.

> Thanks! Will these instructions change once rust-psutil/rust-psutil#75 is fixed?

Yes, but in very ugly way. And they are not relevant for Copr. For example `ytop` is still packaged only for Rawhide. Copr version available for all Fedora's 30+ and even CentOS 7 already.

**Comment by tijptjik** [comment]
Can confirm that the installation instructions work.

**Comment by cjbassi** [comment]
So I actually just updated the readme and I'm now using repology to show the available packages, which makes things easier, so I'm not sure if we need to add this to the readme. Except do you think we should add copr instruction since I don't think repology includes it?

**Comment by tim77** [comment]
Repology will shows versions of current `ytop` releases for all Fedora branches where package available and as for today it still only available for Rawhide branch (`0.5.1` version)
DeepinScreenshot_select-area_20200511225159

Packaging and mainlining Rust software in Fedora is not only **very** time consuming due to lack of infrastructure and automation for Rust stack and because of some [politics](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PEDIYEEYOARB7WW3IMS6GVZ54WPI67LT/) but sometimes not possible for non-Rawhide releases. Until all this will been fixed the COPR is life saver.

So yes, definitely mention COPR link in README would be useful. It's also packaged for CentOS 7 now.

**Comment by cjbassi** [comment]
That makes sense, if you want to update this pull request to mention the copr stuff then I would be happy to add that.

**Comment by cjbassi** [comment]
Thanks!

**Pull request merged**
